variables:
   VERSION: 1.0.${CI_PIPELINE_ID}


stages:
   - build
   - test
   - sonar
   - release
   - deploy


  
include:
  - template: Security/SAST.gitlab-ci.yml 







    
build-frontend-code-job:
  stage: build ##
  variables:  
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install
    - npm run build
    - cd ..
    - mkdir sausage-store-${VERSION}
    - mv frontend/dist/frontend sausage-store-${VERSION}/public_html

  artifacts:
    paths:
    - sausage-store-${VERSION}/public_html 


sonarqube:
  stage: sonar
  image: sonarsource/sonar-scanner-cli
  script:
    - cd frontend
    - >
      sonar-scanner 
      -Dsonar.projectKey=${SONAR_B_PROJECT_KEY}
      -Dsonar.sources=.
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.login=${SONAR_B_LOGIN} 
      -Dsonar.projectName=14_SERGEYKLIMACHEV_BACKEND


release:
   stage: release
   script:
     - tar czvf sausage-store-${VERSION}.tar.gz sausage-store-${VERSION}
     - curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file sausage-store-${VERSION}.tar.gz ${NEXUS_REPO_URL}/sausage-store-klimachev-sergey-frontend/sausage-store/${VERSION}/sausage-store-${VERSION}.tar.gz 
     - curl -X POST -H 'Content-type:application/json' --data '{"chat_id":"-1001823350512", "text":"Вышла новая версия сосисочной — '"$VERSION"' Скачать фронт можно по ссылке — '"$NEXUS_REPO_URL/sausage-store-klimachev-sergey-frontend/sausage-store/$VERSION/sausage-store-$VERSION.tar.gz"' "}' https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage  
   only:
     changes:
     - frontend/**/* 



deploy:
  stage: deploy
  before_script:
  #устанавливаем ssh-agent для удобства  аутентификации по ssh
    - 'command -v ssh-agent >/dev/null || (  apt-get update -y &&  apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
      #сохраняем сгенеренный ранее приватный ключ для раннера
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts 
  script:
    - scp ./frontend/sausage-store-frontend.service ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/sausage-store-frontend.service
    - ssh ${DEV_USER}@${DEV_HOST} "export "CURRENT_VERSION=${VERSION}"; export "VERSION=${VERSION}"; export "DEV_HOST=${DEV_HOST}";export "NEXUS_REPO_URL=${NEXUS_REPO_URL}"; export "NEXUS_REPO_USER=${NEXUS_REPO_USER}"; export "NEXUS_REPO_PASS=${NEXUS_REPO_PASS}";setsid /bin/bash -s " < ./frontend/deploy.sh


