stages:
  - build

  - notify



    
build-frontend-code-job:
  stage: build
  variables:  
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install
    - npm run build
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    reports:
      dotenv: frontend/job.env
    paths:
      - frontend/dist/frontend 


sonarqube-frontend-sast:
  stage: test
  image: 
  script:
    - cd frontend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_F_PROJECT_KEY}
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.login=${SONAR_F_LOGIN} 


telegram-notification-frontend:
  needs:
    - build-frontend-code-job
  stage: notify
  only:
    changes:
    - frontend/*
  script:
    - echo $JOB_ID
    - curl -X POST -H 'Content-type:application/json' --data '{"chat_id":"-1001823350512", "text":"Климачев Сергей cобрал frontend Скачать frontend можно по ссылке — '"$SHOP_URL/-/jobs/$JOB_ID/artifacts/download?file_type=archive"' "}' https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage  
  needs:
    - build-frontend-code-job 
