variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - test
  - sonar
  - notify

  
include:
  - template: Security/SAST.gitlab-ci.yml 







    
build-frontend-code-job:
  stage: build ##
  variables:  
  only:
    changes:
    - frontend/*
  script:        
    - cd frontend
    - npm install
    - npm run build
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    reports:
      dotenv: frontend/job.env
    paths:
      - frontend/dist/frontend 


sonarqube:
  stage: sonar
  image: sonarsource/sonar-scanner-cli
  script:
    - cd frontend
    - >
      sonar-scanner 
      -Dsonar.projectKey=${SONAR_B_PROJECT_KEY}
      -Dsonar.sources=.
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.login=${SONAR_B_LOGIN} 
      -Dsonar.projectName=14_SERGEYKLIMACHEV_BACKEND





telegram-notification:
  needs:
    - build-frontend-code-job
  stage: notify
  only:
    changes:
    - frontend/*
  script:
    - cd frontend/dist
    - tar czvf sausage-store-${VERSION}.tar.gz frontend
    - curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" --upload-file sausage-store-${VERSION}.tar.gz ${NEXUS_REPO_URL}/sausage-store-klimachev-sergey-frontend/sausage-store/${VERSION}/sausage-store-${VERSION}.tar.gz 
    - echo $JOB_ID
    - curl -X POST -H 'Content-type:application/json' --data '{"chat_id":"-1001823350512", "text":"Вышла новая версия сосисочной — '"$VERSION"' Скачать фронт можно по ссылке — '"$NEXUS_REPO_URL/sausage-store-klimachev-sergey-frontend/sausage-store/$VERSION/sausage-store-$VERSION.tar.gz"' "}' https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage  

  needs:
    - build-frontend-code-job 
cache:
  paths:
    - .npm/ # для хранения зависимостей сборки фронтенда 
