version: "3.3"
services:
  backend:
    image:  ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/sausage-store/sausage-backend:latest
    container_name: backend
    restart: always 
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "false"
      SPRING_FLYWAY_ENABLED: "false"
      REPORT_PATH: /opt/log
      LOG_PATH: /opt/log
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      VAULT_ADDR: ${VAULT_ADDR}
    networks:
      - sausage-store

  backend-report:
    image:  ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/sausage-store/sausage-backend-report:latest
    container_name: backend-report
    restart: always 
    environment:
      DB: ${SPRING_DATA_MONGODB_URI}
      PORT: 8080
      VAULT_ADDR: ${VAULT_ADDR}

    networks:
      - sausage-store
      
  frontend:
    image:  gitlab.praktikum-services.ru:5050/std-014-65/sausage-store/sausage-frontend:latest
    container_name: frontend
    restart: always 
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store:
    ipam:
      driver: default
