version: "3.9"
services:
  backend-blue:
    image:  gitlab.praktikum-services.ru:5050/std-014-65/sausage-store/sausage-backend:latest
    container_name: backend-blue
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "false"
      SPRING_FLYWAY_ENABLED: "false"
      VIRTUAL_HOST:  "backend"
    env_file:
      - .env
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6


  backend-green:
    image:  gitlab.praktikum-services.ru:5050/std-014-65/sausage-store/sausage-backend:latest
    container_name: backend-green
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "false"
      SPRING_FLYWAY_ENABLED: "false"
      VIRTUAL_HOST:  "backend"
    env_file:
      - .env
    networks:
      - sausage-store
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6


  backend-report:
    image:  gitlab.praktikum-services.ru:5050/std-014-65/sausage-store/sausage-backend-report:latest
    container_name: backend-report
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always 
    environment:
      DB: ${SPRING_DATA_MONGODB_URI}
      PORT: 8080
    env_file:
      - .env
    networks:
      - sausage-store
      
  frontend:
    image:  gitlab.praktikum-services.ru:5050/std-014-65/sausage-store/sausage-frontend:latest
    container_name: frontend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always 
    environment:
      DEFAULT_HOST: "backend"
      VIRTUAL_PORT: "8080"
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store:
    ipam:
      driver: default
