stages:
  - test
  - build
  - notify

  
include:
  - template: Security/SAST.gitlab-ci.yml 

spotbugs-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository # не забудьте при сборке также указывать эту папку через аргумент -Dmaven.repo.local 




build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    reports:
      dotenv: backend/job.env
    #paths:
   #   - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    paths:
      - ${CI_PROJECT_DIR}/.m2/


telegram-notification-backend:
  stage: notify
  dependencies:
    - build-backend-code-job 
  only:
    changes:
    - backend/*
  script:
    - echo $JOB_ID
    - curl -X POST -H 'Content-type:application/json' --data '{"chat_id":"-1001823350512", "text":"Климачев Сергей cобрал backend Скачать backend можно по ссылке — '"$SHOP_URL/-/jobs/${JOB_ID}/artifacts/download?file_type=archive"' "}' https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage 
  needs:
    - build-backend-code-job

